services:
  guillotine:
    build:
      context: .
      dockerfile: .docker/Dockerfile.ubuntu
    volumes:
      # Mount the entire project directory for development
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
