[package]
name = "guillotine-rs"
version = "0.1.0"
edition = "2021"
authors = ["Guillotine Contributors"]
description = "Safe Rust bindings for the Guillotine EVM implementation"
repository = "https://github.com/evmts/guillotine"
license = "MIT OR Apache-2.0"
keywords = ["ethereum", "evm", "blockchain", "ffi", "zig"]
categories = ["cryptography::cryptocurrencies", "api-bindings"]

[dependencies]
revm = { version = "14.0", features = ["c-kzg", "blst"] }
alloy-primitives = "0.8"
hex = "0.4"
libc = "0.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
bindgen = "0.69"
cc = "1.0"

[[bench]]
name = "evm_comparison"
harness = false

[lib]
name = "guillotine_ffi"
crate-type = ["cdylib", "rlib"]