# GoReleaser configuration for Guillotine CLI
# https://goreleaser.com

version: 2

# Project metadata
project_name: guillotine

# Before hooks - runs before the release
before:
  hooks:
    # Ensure all dependencies are up to date
    - go mod tidy
    # Build the Zig FFI library that Go depends on
    - bash -c 'cd ../.. && zig build -Doptimize=ReleaseFast'

# Build configuration
builds:
  - id: guillotine-cli
    # Main package to build
    main: .
    binary: guil

    # Build for multiple platforms
    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Environment variables for the build
    env:
      - CGO_ENABLED=1

    # Flags passed to go build
    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

    # Build tags
    tags:
      - netgo

    # Override for specific platforms
    overrides:
      # macOS specific settings
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=o64-clang
          - CXX=o64-clang++

      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=oa64-clang
          - CXX=oa64-clang++

      # Linux specific settings
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=gcc

      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc

      # Windows specific settings
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-w64-mingw32-gcc

# Archive configuration
archives:
  - id: default
    format: tar.gz

    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip

    # Files to include in the archive
    files:
      - README.md
      - CLAUDE.md
      - LICENSE*
      - ../../zig-out/lib/libguillotine.*

    # Archive name template
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

# Checksum configuration
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshot configuration (for non-tag builds)
snapshot:
  version_template: "{{ .Tag }}-next"

# Changelog configuration
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo

# Homebrew tap configuration
brews:
  - name: guillotine

    # GitHub repository for the tap
    repository:
      owner: evmts
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Folder inside the repository
    directory: Formula

    # Template for the Homebrew formula
    homepage: "https://github.com/evmts/guillotine"
    description: "High-performance EVM implementation CLI tool"
    license: "MIT"

    # Dependencies
    dependencies:
      - name: zig
        type: build

    # Install script
    install: |
      bin.install "guil"

    # Test script
    test: |
      system "#{bin}/guil", "--version"

    # Additional download strategy for the Zig library
    extra_install: |
      # The Zig library is included in the archive
      lib.install Dir["zig-out/lib/libguillotine.*"]

# Release configuration
release:
  github:
    owner: evmts
    name: guillotine

  # Release name template
  name_template: "{{.ProjectName}} v{{.Version}}"

  # Draft release
  draft: false

  # Prerelease detection
  prerelease: auto

  # Replace existing release
  replace_existing_draft: true

  # Release notes
  header: |
    ## Guillotine CLI {{ .Tag }}

    High-performance EVM implementation with Zig FFI bindings.

  footer: |
    ---

    **Full Changelog**: https://github.com/evmts/guillotine/compare/{{ .PreviousTag }}...{{ .Tag }}

# Announce configuration (optional - can integrate with Discord, Slack, etc.)
announce:
  skip: '{{gt .Patch 0}}'  # Skip patch releases

# Publishers configuration
publishers:
  - name: upload
    ids:
      - default
    disable: false